# -*- coding: utf-8 -*-
"""request.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eghAf1fa5bt8_GK-LATQYjUqUjVwPmMb
"""

import requests

url = 'http://localhost:5000/predict_api'
r = requests.post(url,json={'gdp_per_capita':200, 'new_tests_smoothed_per_thousand':500, 'population_density':60, 'new_tests_per_thousan':5000,'total_tests_per_thousand':8000,'new_tests_smoothed':3,'tests_per_case':5,'new_cases_smoothed_per_million':4000,'new_cases_per_million':50000,'total_cases_per_million':400000})

print(r.json())